log:
  #  日志输出类型 File,CMD,ES
  type: File
  filepath: logs
  filename: system.log
system:
  #  系统服务名
  Name: tem_go_project
  #  环境
  Mode: debug
  #  秘钥
  Secret: XXX
  #  rsa私钥
  RSAPrivate: configs/rsa/private.pem
  #  rsa公钥
  RSAPublic: configs/rsa/public.pem
  #  过期时间（秒）
  TokenExpireTime: 86400
  RedisExpireTime: 3600
  SessionExpireTime: 86400
  #  服务中心ID
  WorkerID: 00001
  #  数据中心ID
  DataCenterID: 00001
  #  fs本地文件系统路径
  FsPath: fs
  #  部署服务器ip
  SysIP: 0.0.0.0
  #  部署服务器端口
  SysPort: 8000
  #  rpc服务端口
  RpcPort: 8002
  #  使用mysql
  UseMysql: true
  #  使用redis
  UseRedis: true
remote:
  #  ES路由
  ESUrl: http://localhost:9200
  #  用户中心路由
  SsoCenter: localhost:8002
smtp:
  Host: "smtp.qq.com"
  Port: ":587"
  User: "*"
  Pass: "*"
user:
  defaultPassword: 123456