database:
  driver : "mysql"
  host : "xxx"
  port : "xxx"
  username : "xxx"
  password : "xxx"
  database : "xxx"

genCode:
  templates_path: "assert/templates/go/tem_go_project"
  dict_path: "assert/templates/go/dict"
  tmplPath: "assert/templates/go/tmpl"
  result_path: "result/lry_code_gen"