apiVersion: v1
kind: ReplicationController
metadata:
  name: tem_go_project #调度对象的全称，全局唯一
spec:
  replicas: 1    #表示创建1个pod副本数量
  selector:
    app: tem_go_project
  template:
    metadata:
      labels:
        app: tem_go_project # pod拥有的标签
    spec:
      volumes:
        - name: tem_go_project-logs
          hostPath:
            path: "/docker/volumes/tem_go_project/logs"
      containers:
        - name: tem_go_project-v1
          image: tem_go_project  # 对应的从docker拉取的镜像名称
          imagePullPolicy: Never # Always, Never, IfNotPresent
          ports:
            - containerPort: 8000   #容器暴露的端口号
            - containerPort: 8002   #容器暴露的端口号
          volumeMounts:
            - name: tem_go_project-logs
              mountPath: /apps/logs
